# Generated by Django 5.2.3 on 2025-07-13 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("current_skills", models.TextField()),
                ("dream_role", models.CharField(max_length=200)),
                ("role_analysis", models.TextField(blank=True)),
                ("skills_gap", models.JSONField(default=list)),
                ("learning_path_data", models.JSONField(default=list)),
                ("timeline", models.TextField(blank=True)),
                ("success_metrics", models.JSONField(default=list)),
                ("career_advice", models.TextField(blank=True)),
                ("networking_tips", models.JSONField(default=list)),
            ],
            options={
                "verbose_name_plural": "Learning Paths",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resume_file", models.FileField(upload_to="resumes/")),
                ("job_description", models.TextField()),
                ("ats_score", models.IntegerField(blank=True, null=True)),
                ("score_explanation", models.TextField(blank=True)),
                ("strengths", models.JSONField(default=list)),
                ("weaknesses", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=list)),
                ("skills_gap", models.JSONField(default=list)),
                ("upskilling_suggestions", models.JSONField(default=list)),
                ("overall_assessment", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Resume Analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeBuilder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("linkedin", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                ("education", models.JSONField(default=list)),
                ("experience", models.JSONField(default=list)),
                ("projects", models.JSONField(default=list)),
                ("skills", models.JSONField(default=dict)),
                ("research_papers", models.JSONField(default=list)),
                ("achievements", models.JSONField(default=list)),
                ("others", models.JSONField(default=list)),
                ("latex_content", models.TextField(blank=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, upload_to="generated_resumes/"),
                ),
            ],
            options={
                "verbose_name_plural": "Resume Builders",
                "ordering": ["-created_at"],
            },
        ),
    ]
