# Generated by Django 5.2.4 on 2025-07-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hirevision", "0002_learningpath_user_resumeanalysis_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningpath",
            name="task_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="task_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="task_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="task_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resumebuilder",
            name="task_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumebuilder",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="resumebuilder",
            name="task_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
