# Generated by Django 5.2.3 on 2025-07-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hirevision", "0005_conversation_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningpath",
            name="dream_role",
            field=models.CharField(max_length=500),
        ),
    ]
