# Generated by Django 5.2.3 on 2025-08-06 02:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hirevision", "0006_alter_learningpath_dream_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("search_query", models.CharField(max_length=500)),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("user_search", "User Search"),
                            ("resume_analysis", "Resume Analysis"),
                            ("learning_path", "Learning Path"),
                            ("resume_builder", "Resume Builder"),
                            ("thread_search", "Thread Search"),
                            ("general_search", "General Search"),
                        ],
                        max_length=50,
                    ),
                ),
                ("search_results_count", models.IntegerField(default=0)),
                ("search_filters", models.JSONField(blank=True, default=dict)),
                ("search_location", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_successful", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Search Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
