# Generated by Django 5.2.3 on 2025-08-06 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hirevision", "0007_searchhistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SearchHistory",
        ),
    ]
