# Generated by Django 5.2.4 on 2025-08-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hirevision", "0009_user_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
